package utils

import (
	"fmt"
	"os"
	"strings"

	"github.com/jung-kurt/gofpdf"
)

// GeneratePDFReport 生成 PDF 分析报告
func GeneratePDFReport(filename, reportMD, outputPath string) error {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetAutoPageBreak(true, 15)

	// 设置中文字体（使用内置字体，中文可能显示为方框）
	pdf.SetFont("Helvetica", "B", 16)

	// 标题
	pdf.Cell(40, 10, "Malware Analysis Report")
	pdf.Ln(12)

	// 文件名
	pdf.SetFont("Helvetica", "", 12)
	pdf.Cell(40, 8, fmt.Sprintf("File: %s", filename))
	pdf.Ln(10)

	// 处理 Markdown 内容
	lines := strings.Split(reportMD, "\n")
	for _, line := range lines {
		// 跳过空行
		if strings.TrimSpace(line) == "" {
			pdf.Ln(4)
			continue
		}

		// 处理标题
		if strings.HasPrefix(line, "# ") {
			pdf.SetFont("Helvetica", "B", 14)
			pdf.Ln(4)
			pdf.MultiCell(0, 6, strings.TrimPrefix(line, "# "), "", "L", false)
			pdf.Ln(2)
			continue
		}
		if strings.HasPrefix(line, "## ") {
			pdf.SetFont("Helvetica", "B", 12)
			pdf.Ln(3)
			pdf.MultiCell(0, 6, strings.TrimPrefix(line, "## "), "", "L", false)
			pdf.Ln(2)
			continue
		}
		if strings.HasPrefix(line, "### ") {
			pdf.SetFont("Helvetica", "B", 11)
			pdf.Ln(2)
			pdf.MultiCell(0, 5, strings.TrimPrefix(line, "### "), "", "L", false)
			pdf.Ln(1)
			continue
		}

		// 处理粗体
		if strings.HasPrefix(line, "**") && strings.HasSuffix(line, "**") {
			pdf.SetFont("Helvetica", "B", 10)
			text := strings.TrimPrefix(strings.TrimSuffix(line, "**"), "**")
			pdf.MultiCell(0, 5, text, "", "L", false)
			continue
		}

		// 处理代码块
		if strings.HasPrefix(line, "```") {
			continue // 跳过代码块标记
		}

		// 处理表格分隔线
		if strings.HasPrefix(line, "|--") || strings.HasPrefix(line, "| --") {
			continue
		}

		// 处理表格行
		if strings.HasPrefix(line, "|") {
			pdf.SetFont("Courier", "", 8)
			// 简化表格显示
			cells := strings.Split(line, "|")
			var rowText string
			for _, cell := range cells {
				if strings.TrimSpace(cell) != "" {
					rowText += strings.TrimSpace(cell) + " | "
				}
			}
			if rowText != "" {
				pdf.MultiCell(0, 4, rowText, "", "L", false)
			}
			continue
		}

		// 处理分隔线
		if strings.HasPrefix(line, "---") {
			pdf.Ln(2)
			pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
			pdf.Ln(2)
			continue
		}

		// 处理 JSON 内容（通常很长，需要特殊处理）
		if strings.HasPrefix(line, "{") || strings.HasPrefix(line, "}") || strings.HasPrefix(line, "  \"") {
			pdf.SetFont("Courier", "", 7)
			// 截断过长的行
			if len(line) > 100 {
				line = line[:100] + "..."
			}
			pdf.MultiCell(0, 4, line, "", "L", false)
			continue
		}

		// 普通文本
		pdf.SetFont("Helvetica", "", 10)
		// 截断过长的行
		if len(line) > 120 {
			line = line[:120] + "..."
		}
		pdf.MultiCell(0, 5, line, "", "L", false)
	}

	// 页脚
	pdf.Ln(10)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.Cell(0, 10, "Generated by SkillHub Malware Analysis System")

	// 保存文件
	return pdf.OutputFileAndClose(outputPath)
}

// GenerateSimplePDF 生成简单的 PDF 报告（仅包含基本信息）
func GenerateSimplePDF(filename, content, outputPath string) error {
	// 确保目录存在
	dir := strings.TrimSuffix(outputPath, "/"+strings.Split(outputPath, "/")[len(strings.Split(outputPath, "/"))-1])
	if dir != "" {
		os.MkdirAll(dir, 0755)
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetAutoPageBreak(true, 15)

	// 标题
	pdf.SetFont("Helvetica", "B", 16)
	pdf.Cell(0, 10, "Malware Analysis Report")
	pdf.Ln(12)

	// 文件名
	pdf.SetFont("Helvetica", "", 12)
	pdf.Cell(0, 8, fmt.Sprintf("File: %s", filename))
	pdf.Ln(10)

	// 内容
	pdf.SetFont("Courier", "", 8)
	pdf.MultiCell(0, 4, content, "", "L", false)

	// 页脚
	pdf.Ln(10)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.Cell(0, 10, "Generated by SkillHub Malware Analysis System")

	return pdf.OutputFileAndClose(outputPath)
}
